### ISSUE TITLE
Add heroku deploy support

### ISSUE THREAD

**Issue by askfriends** [CrypticSignal/av-converter#21]
Can you add heroku deploy support?

**Comment by CrypticSignal** [comment]
I've never deployed something to Heroku before and it's not really something that I'm interested in figuring out. What would the benefit be?

**Comment by askfriends** [comment]
> I've never deployed something to Heroku before and it's not really something that I'm interested in figuring out. What would the benefit be?

heroku offers free hours for 20days and if we add CC it allows another 15days so it means we can host our app for free and unlimited bandwidth.
Its easy and offers high speed bandwidth

**Comment by CrypticSignal** [comment]
The server that https://av-converter.com runs on has unlimited bandwidth and as I am paying for the server, it is free for everyone else including you. Adding Heroku support to this project is not something that I want to spend my time on figuring out, at least not at this moment in time. You are free to give it a go yourself and submit a pull request if you are successful.
