### ISSUE TITLE
Blank page on Firefox

### ISSUE THREAD

**Issue by Mte90** [CrypticSignal/av-converter#23]
So I have Firefox with third part blocker with privacy badger and ublock origin and I get a blank page.

Those are the errors I see in console so I guess that something about tracking is crashing the whole app.

![immagine](https://user-images.githubusercontent.com/403283/147761418-d19c996f-d01d-479b-ae19-f6d5c6e55d3b.png)

**Comment by CrypticSignal** [comment]
The issue was not related to Firefox, your third-party blocker or uBlock. I have fixed the issue. Please try my website again and confirm whether it works now.

**Comment by Mte90** [comment]
Now works :-)
